export default {
    deleteTest: '[data-context="resource"][data-action="removeNode"]',
    deleteClass: '[data-context="resource"][data-action="removeNode"]',
    moveClass: '[id="class-move-to"][data-context="class"][data-action="moveTo"]',
    moveConfirmSelector: 'button[data-control="ok"]',
    addTest: '[data-context="resource"][data-action="instanciate"]',
    testForm: 'form[action="/taoTests/Tests/editTest"]',
    testClassForm: 'form[action="/taoTests/Tests/editClassLabel"]',
    deleteConfirm: '[data-control="ok"]',
    root: '[data-uri="http://www.tao.lu/Ontologies/TAOTest.rdf#Test"]',
    classOptions: '[action="/tao/PropertiesAuthoring/index"]',
    editClass: '#test-class-schema',
    editClassLabelUrl: 'taoTests/Tests/editClassLabel',
    editClassUrl: 'tao/PropertiesAuthoring/index',
    propertyEdit: 'div[class="form-group property-block regular-property property-edit-container-open"]',
    treeRenderUrl: 'taoTests/Tests',
    addSubClassUrl: 'taoTests/Tests/addSubClass',
    restResourceGetAll: 'tao/RestResource/getAll',
    resourceRelations: 'tao/ResourceRelations',
    editTestUrl: 'taoTests/Tests/editTest',
    deleteTestUrl: 'taoTests/Tests/delete'
};
