

INSERT INTO `models` (`modelID`, `modelURI`, `baseURI`) VALUES
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#', 'http://www.tao.lu/Ontologies/TAOTest.rdf#');



INSERT INTO `statements` (`modelID`, `subject`, `predicate`, `object`, `l_language`, `author`, `stread`, `stedit`, `stdelete`) VALUES
(8, 'lg', 'lg', 'lg', 'FR', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(8, 'lg', 'lg', 'lg', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(8, 'lg', 'lg', 'lg', 'DE', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(8, 'lg', 'lg', 'lg', 'PT', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/Ontologies/TAOTest.rdf#Test', '', 'generis', 'yy-[admin,administrators,authors]', 'yy-[admin,administrators,authors]', 'yy-[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://www.tao.lu/Ontologies/TAOTest.rdf#RelatedItems', 'http://127.0.0.1/middleware/demoItems.rdf#125187684965350', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.tao.lu/Ontologies/generis.rdf#False', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://www.w3.org/2000/01/rdf-schema#comment', '&nbsp;', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://www.w3.org/2000/01/rdf-schema#label', 'myCTest\r\n', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://www.w3.org/2000/01/rdf-schema#seeAlso', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy', ' ', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy', ' ', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.w3.org/2000/01/rdf-schema#label', 'Active\r\n', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.w3.org/2000/01/rdf-schema#seeAlso', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.w3.org/2000/01/rdf-schema#comment', 'active / inactive state\r\n', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/Ontologies/TAOTest.rdf#Test', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#RadioBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125187505335708', 'http://www.tao.lu/Ontologies/TAOTest.rdf#TestContent', '<?xml version=''1.0'' encoding=''UTF-8'' ?>\r\n<tao:TEST xmlns:rdf=''http://www.w3.org/1999/02/22-rdf-syntax-ns#'' rdf:ID="http://127.0.0.1/middleware/demo.rdf#125187505335708" xmlns:tao=''http://www.tao.lu/tao.rdfs#'' xmlns:rdfs=''http://www.w3.org/TR/1999/PR-rdf-schema-19990303#''><rdfs:LABEL lang="EN"></rdfs:LABEL>\r\n	<rdfs:COMMENT lang="EN"></rdfs:COMMENT><tao:TESTPRESENTATION><xul><stylesheet id="test_stylesheet" src="./test.css"/><box id="testContainer_box">\r\n<label id="testLabel_label" left="10" top="10" class="Label" value="&lt;b&gt;&lt;u&gt;#{XPATH(/tao:TEST/rdfs:LABEL)}#&lt;/u&gt;&lt;/b&gt;" style=''''/>\r\n\r\n								<label id="testComment_label" left="25" top="30" class="Comment" value="#{XPATH(/tao:TEST/rdfs:COMMENT)}#"/><box id="itemContainer_box" left="100" top="65"/>\r\n		\r\n		<button id="nextItem_button" left="200" url="http://www.tao.lu/middleware/itempics/default/right.swf" top="400" label="Next" image="item_next.jpg" disabled="true" oncommand="tao_test.nextItem"/><progressmeter id="test_progressmeter" left="" top="" mode="determined" value="0"/><listbox id="testItems_listbox" left="10" top="10" height="400" width="100"/>\r\n        		<box id="testLanguages_box" left="10" top="475">\r\n        		    <button id="language_FR_button" left="0" top="0" label="FR" image="flag_FR.jpg" disabled="false" oncommand="tao_test.setLang(FR)"/>\r\n        		    <button id="language_DE_button" left="60" top="0" label="DE" image="flag_DE.jpg" disabled="false" oncommand="tao_test.setLang(DE)"/>\r\n        		</box></box></xul></tao:TESTPRESENTATION>	<tao:PASSWORD>123456</tao:PASSWORD><tao:DURATION>600</tao:DURATION>	<tao:HASSEQUENCEMODE  >SEQUENTIAL</tao:HASSEQUENCEMODE><tao:PREVIEW>FALSE</tao:PREVIEW><tao:REVIEW>FALSE</tao:REVIEW><tao:HOLDABLE>TRUE</tao:HOLDABLE><tao:RESPONSEPATTERN>dichotomic</tao:RESPONSEPATTERN><tao:HASSCORINGMETHOD Qmin="" Qmax="" Qiter="">CLASSICAL RATIO</tao:HASSCORINGMETHOD><tao:TESTLISTENERS></tao:TESTLISTENERS><tao:CUMULMODEL>CLASSICAL</tao:CUMULMODEL><tao:LAUNCH plugin="CLLPlugin"><cll:threshold></cll:threshold><cll:threshold></cll:threshold><cll:threshold></cll:threshold></tao:LAUNCH>\r\n<tao:CITEM weight="" Sequence="">1</tao:CITEM>\r\n<tao:CITEM weight="" Sequence="">2</tao:CITEM>\r\n<tao:CITEM weight="" Sequence="">3</tao:CITEM>\r\n<tao:CITEM weight="" Sequence="">4</tao:CITEM>\r\n<tao:CITEM weight="" Sequence="">5</tao:CITEM>\r\n<tao:CITEM weight="" Sequence=""></tao:CITEM></tao:TEST>', 'EN', 'generis', 'yy-[admin,administrators,authors]', 'yy-[admin,administrators,authors]', 'yy-[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/Ontologies/generis.rdf#Boolean', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(8, 'http://127.0.0.1/middleware/demo.rdf#125302864843898', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#Test', 'http://www.w3.org/2000/01/rdf-schema#label', 'Test', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#Test', 'http://www.w3.org/2000/01/rdf-schema#comment', 'Test', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#Test', 'http://www.w3.org/2000/01/rdf-schema#subClassOf', 'http://www.tao.lu/Ontologies/TAO.rdf#TAOObject', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#RelatedItems', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#RelatedItems', 'http://www.w3.org/2000/01/rdf-schema#label', 'Related Items', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#RelatedItems', 'http://www.w3.org/2000/01/rdf-schema#comment', 'Related Items', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#RelatedItems', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/Ontologies/TAOTest.rdf#Test', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#RelatedItems', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/Ontologies/TAOItem.rdf#Item', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#RelatedItems', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#TreeView', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/Ontologies/generis.rdf#Model', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf', 'http://www.w3.org/2000/01/rdf-schema#label', 'TAO Test Model', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf', 'http://www.w3.org/2000/01/rdf-schema#comment', 'TAO Test Model', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf', 'http://www.tao.lu/Ontologies/generis.rdf#Plugin', 'hypergraph', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#TestContent', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#TestContent', 'http://www.w3.org/2000/01/rdf-schema#label', 'TestContent', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#TestContent', 'http://www.w3.org/2000/01/rdf-schema#comment', 'TestContent', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#TestContent', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/Ontologies/TAOTest.rdf#Test', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#TestContent', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.w3.org/2000/01/rdf-schema#Literal', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(9, 'http://www.tao.lu/Ontologies/TAOTest.rdf#TestContent', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#TAuthoring', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]');
